# This is a basic workflow to help you get started with Actions

name: Basic CI

# Controls when the workflow will run
on:
  push:
    branches: ['main']

  workflow_dispatch:

env:
  SECRETS_BASE64: ${{ secrets.SECRETS_BASE64 }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'release')"
    # if: "contains(github.event.head_commit.message, 'release')"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Load environment variables
        run: |
          echo Creating .env file...
          echo $SECRETS_BASE64 | base64 -d > .env

      - name: Run tests
        run: |
          cat .env
          npm ci
          npm run test

      - name: Show message
        run: |
          echo "Uhuuu! passed on tests!!!"

  lint-commits:
    name: Lint Commits
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'release')"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4
