name: Test CI

on:
  push:
    branches: ['main']

  release:
    types: [released]
  workflow_dispatch:

env:
  TEST_ENV_VARS: ${{ secrets.TEST_ENV_VARS }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
         token: ${{ secrets.REPO_SCOPED_TOKEN }}

      - name: Wait 
        run: |
          sleep 10

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
         token: ${{ secrets.REPO_SCOPED_TOKEN }}

      - name: Do something 
        run: |
          sleep 5 

      - name: Call deploy action
        uses: actions/github-script@v6
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        with:
          script: |
            const sleepForOtherJob = require('./.github/scripts/sleepForOtherJob.js')
            await sleepForOtherJob({github, context, jobName: 'test'})

      - name: Do other thing if required job has ended with success 
        run: |
          echo 'uhuuuuuu!'
