name: Test CI

on:
  push:
    branches: ['main']

  release:
    types: [released]
  workflow_dispatch:

jobs:
  wait:
    runs-on: ubuntu-latest
    steps:
      - name: Call notification
        run: |
          sleep 10
          false

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Wait until test finishes
        uses: NathanFirmo/wait-for-other-job@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          job: 'wait'

      - name: Wait for other action
        uses: NathanFirmo/wait-for-other-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          workflow: 'wait.yml'

      - name: Done
        run: echo done

