name: Test CI

on:
  push:
    branches: ['main']

  release:
    types: [released]
  workflow_dispatch:

env:
  TEST_ENV_VARS: ${{ secrets.TEST_ENV_VARS }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
         token: ${{ secrets.REPO_SCOPED_TOKEN }}

      - name: Wait 
        run: |
          sleep 60 

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
         token: ${{ secrets.REPO_SCOPED_TOKEN }}

      - name: Wait 
        run: |
          sleep 10 

      - name: Echo
        run: |
          echo ${{ jobs }}
          
