name: Test CI

on:
  push:
    branches: ['main']

  release:
    types: [released]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Wait 
        uses: NathanFirmo/wait-for-other-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          workflow: 'sample.yml'
