name: Test CI

on:
  push:
    branches: ['main']

  release:
    types: [released]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Call notification
        run: |
          curl --request POST \
            --url '${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}' \
            --header 'Content-Type: application/json' \
            --data '{
            "text": "Teste"
          }'
