name: Test CI

on:
  push:
    branches: ['main']

  release:
    types: [released]
  workflow_dispatch:

env:
  TEST_ENV_VARS: ${{ secrets.TEST_ENV_VARS }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
         token: ${{ secrets.REPO_SCOPED_TOKEN }}

      - name: Wait 
        run: |
          sleep 10 

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
         token: ${{ secrets.REPO_SCOPED_TOKEN }}

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Call deploy action
        uses: actions/github-script@v6
        with:
          script: |
            const res = github.rest.actions.listJobsForWorkflowRunAttempt({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: ${{ env.GITHUB_RUN_ID }},
              attempt_number: ${{ env.GITHUB_RUN_ATTEMPT }},
            })            
            console.log(res)

