name: Test CI

on:
  push:
    branches: ['main']

  release:
    types: [released]
  workflow_dispatch:

env:
  TEST_ENV_VARS: ${{ secrets.TEST_ENV_VARS }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
         token: ${{ secrets.REPO_SCOPED_TOKEN }}

      - name: Wait 
        run: |
          sleep 10 

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
         token: ${{ secrets.REPO_SCOPED_TOKEN }}

      - name: Call deploy action
        uses: actions/github-script@v6
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        with:
          script: |
           const envContext = JSON.parse(process.env.GITHUB_CONTEXT)
           const res = await github.rest.actions.listJobsForWorkflowRunAttempt({
             owner: context.repo.owner,
             repo: context.repo.repo,
             run_id: envContext.run_id,
             attempt_number: envContext.run_attempt,
           })            
           console.log({res})

