name: Wait CI

on:
  push:
    branches: ['main']

  release:
    types: [released]
  workflow_dispatch:

jobs:
  wait:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep
        run: |
          sleep 60
          false
